// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCokKWBRS5EhCkmH7rzz3sCiizcXqdyalw',
    appId: '1:385231785507:web:db37d89f26fa65bebd2b96',
    messagingSenderId: '385231785507',
    projectId: 'fir-minerapp',
    authDomain: 'fir-minerapp.firebaseapp.com',
    storageBucket: 'fir-minerapp.appspot.com',
    measurementId: 'G-GKS6EZVB64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk20h23GF8dWKhcFY2NuSTw4oa-j286S0',
    appId: '1:385231785507:android:761115ebef8fa058bd2b96',
    messagingSenderId: '385231785507',
    projectId: 'fir-minerapp',
    storageBucket: 'fir-minerapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5oq5l4XS_GmRNIEXO-JGN2dpCZfYSqSk',
    appId: '1:385231785507:ios:b69a19762c0dea4cbd2b96',
    messagingSenderId: '385231785507',
    projectId: 'fir-minerapp',
    storageBucket: 'fir-minerapp.appspot.com',
    iosBundleId: 'com.example.firebaseMiner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5oq5l4XS_GmRNIEXO-JGN2dpCZfYSqSk',
    appId: '1:385231785507:ios:b69a19762c0dea4cbd2b96',
    messagingSenderId: '385231785507',
    projectId: 'fir-minerapp',
    storageBucket: 'fir-minerapp.appspot.com',
    iosBundleId: 'com.example.firebaseMiner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCokKWBRS5EhCkmH7rzz3sCiizcXqdyalw',
    appId: '1:385231785507:web:eb55c995bea40423bd2b96',
    messagingSenderId: '385231785507',
    projectId: 'fir-minerapp',
    authDomain: 'fir-minerapp.firebaseapp.com',
    storageBucket: 'fir-minerapp.appspot.com',
    measurementId: 'G-5BX7L1MVKK',
  );
}
